IN-PROGRESS
w3c/wai-accessibility-principles pull request #19
Opened 2019-06-22 15:18 UTC by rumoroso

2019-06-24 20:35 UTC, slhenry commented
Hi Jorge,

In the footer text (which is near the top of the source page), please do *translate* "Updated 10 May 2019."

(I will update the instructions so it's more clear to translate the date, yet not change the date. :-)

For the list items linked under "WCAG", please check that they are the same as in [WCAG 2 Spanish Translation](http://www.sidar.org/traducciones/wcag20/es/). If you have any questions about the text, you can work with Martin/@espinr and Emmanuelle on wording.

Thanks!

2019-06-24 20:54 UTC, rumoroso commented
@espinr , could you please collaborate in the review or let me know who could do it?
Thanks in advance

2019-06-24 20:59 UTC, rumoroso commented
> In the footer text (which is near the top of the source page), please do _translate_ "Updated 10 May 2019."
Sure

> For the list items linked under "WCAG", please check that they are the same as in [WCAG 2 Spanish Translation](http://www.sidar.org/traducciones/wcag20/es/).> For the list items linked under "WCAG", please check that they are the same as in [WCAG 2 Spanish Translation](http://www.sidar.org/traducciones/wcag20/es/).
If I understood correctly, you mean that the links should point to the corresponding sections in that document.

I'll update everything and commit the changes.

Thank you for your really fast feed back :)

2019-06-25 06:26 UTC, espinr commented
> @espinr , could you please collaborate in the review or let me know who could do it?

Sure!

2019-06-25 07:07 UTC, slhenry commented
> If I understood correctly, you mean that the links should point to the corresponding sections in that document.

Oh dear, I was not clear enough. (sad face)
I just meant that the *text* wording of the link should be the same *text* as in the translation.

Although, it makes sense to link to the Spanish translation once it is complete.

Please leave it as you have it for now and I will figure out what to do...

2019-06-25 07:31 UTC, rumoroso commented
Hi, it was not your fault, but just my misunderstanding and that it is the first time I do this collaboration, so just time and experience for being aligned in what we say and others understand ;)

> Oh dear, I was not clear enough. (sad face)
> I just meant that the _text_ wording of the link should be the same _text_ as in the translation.

2019-06-25 07:36 UTC, slhenry commented
I greatly appreciate your contributions and collaboration.

We are refining our translations instructions and process, too. So I also appreciate your patience. :-)

2019-06-25 13:09 UTC, espinr requested changes
@rumoroso, many thanks!!! Some minor typos and suggestions. I think it's a good quality translation. Thanks

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Ilya, ejecutiva senior que con ceguera](/people-use-web/user-stories/#accountant)
minor typo: 
`[Ilya, ejecutiva senior con ceguera](/people-use-web/user-stories/#accountant)`

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Yun, retirada, con baja visión, temblores en manos y leve perdida de memoria a corto plazo](/people-use-web/user-stories/#retiree)
proposal: 
baja visión > visión reducida

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +Las personas que no pueden oir audio o ver video necesitan alternativas. Entre los ejemplos se incluyen:
oir > oír

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Ilya, ejecutiva senior que con ceguera](/people-use-web/user-stories/#accountant)
minor typo:
`[Ilya, ejecutiva senior con ceguera](/people-use-web/user-stories/#accountant)`

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   El orden de la información o la secuendia de instrucciones sean independientes de la presentación
secuendia > secuencia

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Lee, comprador online con ceguera para el color](/people-use-web/user-stories/#shopper)
proposal:
`[Lee, comprador online con daltonismo](/people-use-web/user-stories/#shopper)`

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Yun, retirada, con baja visión, temblores en manos y leve perdida de memoria a corto plazo](/people-use-web/user-stories/#retiree)
proposal:
baja visión > visión reducida

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Lee, comprador online con ceguera para el color](/people-use-web/user-stories/#s#reporter)
proposal: daltonismo

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Ilya, ejecutiva senior que con ceguera](/people-use-web/user-stories/#accountant)
`[Ilya, ejecutiva senior con ceguera](/people-use-web/user-stories/#accountant)`

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +### Funcionalidad está disponible desde el teclado {#keyboard}
proposal:
`### Funcionalidad disponible desde el teclado {#keyboard}`

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +El cumplimiento de este requisito ayuda a los usuarios de teclado, incluidos quienes que utilizan teclados alternativos, como teclados con diseños ergonómicos, teclados en pantalla o dispositivos de
(entrada de voz) > (entrada por voz)?

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Ilya, ejecutiva senior que con ceguera](/people-use-web/user-stories/#accountant)
`[Ilya, ejecutiva senior con ceguera](/people-use-web/user-stories/#accountant)`

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +Entre los ejemplos de como proporcionar tiempo suficiente se incluyen los mecanismos para:
como > cómo

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   Pausar, detener u ocultar movimiento, parpadeo o scroll de contenido
proposal: scroll > desplazamiento del

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   Re-autenticar cuando la sesion expire sin perdida de datos
sesión

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Yun, retirada, con baja visión, temblores en manos y leve perdida de memoria a corto plazo](/people-use-web/user-stories/#retiree)
proposal: visión reducida

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Kaseem, adolescente con sordera y cegera](/people-use-web/user-stories/#teenager)
cegera > ceguera

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Lee, comprador online con cegera para el color](/people-use-web/user-stories/#shopper)
cegera > ceguera

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Kaseem, adolescente con sordera y cegera](/people-use-web/user-stories/#teenager)
cegera > ceguera

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Ilya, profesional senior con cegera](/people-use-web/user-stories/#accountant)
cegera > ceguera

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Lee, comprador online con cegera para el color](/people-use-web/user-stories/#shopper)
cegera > ceguera

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Ilya, profesional senior con cegera](/people-use-web/user-stories/#accountant)
cegera > ceguera

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Kaseem, adolescente con sordera y cegera](/people-use-web/user-stories/#teenager)
cegera > ceguera

2019-06-25 13:09 UTC, espinr commented on index.es.md
> +-   [Ilya, profesional senior con cegera](/people-use-web/user-stories/#accountant)
cegera > ceguera

2019-06-25 13:27 UTC, rumoroso commented
Hi Martín (@espinr ), thanks for the review. It was clear this is not your first time you but also that it was for me ;)
Changes applied

2019-06-26 17:10 UTC, slhenry commented
Hi @cmunch

Please take a quick look at this page to help with the coordination: https://deploy-preview-19--wai-accessibility-principles.netlify.com/fundamentals/accessibility-principles/es

If all looks good, we'll have more translations to publish! :-)

2019-06-28 12:56 UTC, espinr commented
> Hi Martín (@espinr ), thanks for the review. It was clear this is not your first time you but also that it was for me ;)

Yep! Sorry, but I started the review early in the morning, (several meetings and interruptions in the middle) and I finished it several hours after. So I worked on a outdated version. My apologies.

2019-07-02 05:57 UTC, merged